### PR TITLE
Fix calendar bugs

### LINKED ISSUE #255: Moving the calendar around does not load more posts
As you navigate from month to month it should be loading more posts. it's not right now

### PR DESCRIPTION
**Pull request by KevinTriplett**
Closes #255

[This commit](https://github.com/Hylozoic/hylo/commit/1c71912e26e8f79d259bfa72938d934e75a3fa42) is something that needs close review

### CODE REVIEW

File: apps/web/src/components/Calendar/header/date/calendar-header-date-badge.tsx [hunk 1]
```diff
@@ -8,7 +8,7 @@ export default function CalendarHeaderDateBadge () {
 
   return (
     <div className='whitespace-nowrap rounded-sm border px-1.5 py-0.5 text-xs'>
-      {monthEvents.length} events
+      {monthEvents.length === 0 ? 'No' : monthEvents.length} events
```
Comment (tibetsprague) [inline apps/web/src/components/Calendar/header/date/calendar-header-date-badge.tsx:11]: this will need to be translated - see useTranslation and en.json, es.json

File: apps/web/src/components/Calendar/header/date/calendar-header-date-chevrons.tsx [hunk 2]
```diff
@@ -47,7 +47,7 @@ export default function CalendarHeaderDateChevrons () {
       </Button>
 
       <span className='min-w-[140px] text-center font-medium'>
-        {DateTime.fromJSDate(date).toFormat('MMMM d, yyyy')}
+        {DateTime.fromJSDate(date).toFormat('MMMM yyyy')}
```
Comment (tibetsprague) [inline apps/web/src/components/Calendar/header/date/calendar-header-date-chevrons.tsx:50]: flag for the future - cover the date time format to the local format used by people around the world in their country

File: apps/web/src/routes/Stream/Stream.js [hunk 3]
```diff
@@ -122,6 +127,10 @@ export default function Stream (props) {
 
   const topics = topic ? [topic.id] : customView?.type === 'stream' ? customView?.topics?.toModelArray().map(t => t.id) : []
 
+  // for calendar viewmode
+  const [mode, setMode] = useState('month')
```
Comment (tibetsprague) [inline apps/web/src/routes/Stream/Stream.js:131]: can we use calendarMode for this variable name?

File: apps/web/src/routes/Stream/Stream.js [hunk 4]
```diff
@@ -122,6 +127,10 @@ export default function Stream (props) {
...
+  const [date, setDate] = useState(new Date())
```
Comment (tibetsprague) [inline apps/web/src/routes/Stream/Stream.js:132]: calendarDate?

**Review by tibetsprague — CHANGES_REQUESTED** [review]

File: apps/web/src/components/Calendar/header/date/calendar-header-date-badge.tsx [hunk 5]
```diff
@@ -1,14 +1,16 @@
...
 
 export default function CalendarHeaderDateBadge () {
   const { events, date } = useCalendarContext()
   const monthEvents = events.filter((event) => sameMonth(event.start, date))
+  const { t } = useTranslation()
 
   return (
     <div className='whitespace-nowrap rounded-sm border px-1.5 py-0.5 text-xs'>
-      {monthEvents.length} events
+      {`${monthEvents.length === 0 ? t('No') : monthEvents.length} ${t('Events')}`}
```
Comment (tibetsprague) [inline apps/web/src/components/Calendar/header/date/calendar-header-date-badge.tsx:13]: there is a better way to have the translation handle pluralization, but i wont make you do it right now :) 

e.g.
"voterCount_one": "with {{count}} vote",
  "voterCount_other": "with {{count}} votes",

File: apps/web/src/components/Calendar/header/date/calendar-header-date-chevrons.tsx [hunk 6]
```diff
@@ -47,7 +57,7 @@ export default function CalendarHeaderDateChevrons () {
       </Button>
 
       <span className='min-w-[140px] text-center font-medium'>
-        {DateTime.fromJSDate(date).toFormat('MMMM d, yyyy')}
+        {DateTime.fromJSDate(date).toLocaleString(dateFormat)}
```
Comment (tibetsprague) [inline apps/web/src/components/Calendar/header/date/calendar-header-date-chevrons.tsx:60]: awesome! thanks for doing this. something we have to do throughout the app...

File: apps/web/src/components/PostEditor/PostEditor.js [hunk 7]
```diff
@@ -192,7 +192,7 @@ function PostEditor ({
   const toOptions = useMemo(() => {
     return groupOptions.map((g) => [{ id: 'group_' + g.id, name: g.name, avatarUrl: g.avatarUrl, group: g }]
       .concat(g.chatRooms.toModelArray()
-        .map((cr) => ({ id: cr.groupTopic.id, group: g, name: g.name + ' #' + cr.groupTopic.topic.name, topic: cr.groupTopic.topic, avatarUrl: g.avatarUrl }))
+        .map((cr) => ({ id: cr.groupTopic?.id, group: g, name: g.name + ' #' + cr.groupTopic?.topic.name, topic: cr.groupTopic?.topic, avatarUrl: g.avatarUrl }))
```
Comment (tibetsprague) [inline apps/web/src/components/PostEditor/PostEditor.js:195]: i actually fixed this on dev in a better way, but this is ok too

**Review by tibetsprague — APPROVED** [review]
