### PR TITLE
493-mobile-group-context-fix

### LINKED ISSUE #493: Click on some Push notifications going to the wrong group
I have seen this sometimes, but not every time. When it does it takes me to some random group I have not visited in a long time

### PR DESCRIPTION
**Pull request by lorenjohnson**
- Fixes #493: ChatWebView was always using originalLinkingPath even when currentGroup.slug changed. Now it re-constructs path using currentGroup and the parsed path params
- Updates membership lastViewedAt on change to group, which seemed to be currently relying upon the update within WebView Chat
- Simplifies some HyloWebView implementation details for "handled routes" 
- Fixes currentGroup switch double-nav event (https://github.com/Hylozoic/hylo/issues/435 / https://github.com/Hylozoic/hylo/issues/528)
- Update GroupSettingsWebView to also not rely exclusively on originalLinkingPath to fix the same issue: currently when in group settings and then linking to another screen in another group, the settings screen will not update to the newly selected current group

### CODE REVIEW

**Comment by thomasgwatson** [comment]
🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

File: apps/mobile/src/screens/GroupSettingsWebView/GroupSettingsWebView.js [hunk 1]
```diff
@@ -1,27 +1,18 @@
-import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
+import React, { useCallback } from 'react'
 import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
 import { useFocusEffect, useNavigation } from '@react-navigation/native'
 import useGroup from '@hylo/hooks/useGroup'
 import useRouteParams from 'hooks/useRouteParams'
-import HyloWebView from 'components/HyloWebView'
+import HyloWebView from 'components/HyloWebView/HyloWebView'
```
Comment (thomasgwatson) [inline apps/mobile/src/screens/GroupSettingsWebView/GroupSettingsWebView.js:6]: Does this matter? Importing it directly instead of via its index?

**Review by thomasgwatson — APPROVED** [review]
lgtm, just one little question

File: apps/mobile/src/screens/GroupSettingsWebView/GroupSettingsWebView.js (hunk 1 above)
Comment (lorenjohnson) [reply apps/mobile/src/screens/GroupSettingsWebView/GroupSettingsWebView.js]: Good catch. It won't break anything, but isn't correct. My auto-import in Visual Studio code does this by default and sometimes forget to correct it. Fixed now.
