### PR TITLE
fix(web): HyloEditorMobile moves to create ready instead of onBeforeCreate, fixes #109

### LINKED ISSUE #109: Commenting on a sub-comment breaks the comment box
Clicking on the reply to a comment that is already a child/sub comment of someone else's comment brings up the comment box without the ability to type into it

### PR DESCRIPTION
**Pull request by lorenjohnson**
fix #109

### CODE REVIEW

File: apps/web/src/components/HyloEditor/HyloEditor.js [hunk 1]
```diff
@@ -34,100 +34,124 @@ const HyloEditor = React.forwardRef(({
...
-          return {
-            Enter: ({ editor }) => {
-              if (!onEnter) return false
-              return onEnter(editor.getHTML())
-            },
-            Escape: () => {
-              if (!onEscape) return false
-              return onEscape()
-            }
+  const extensions = [
```
Comment (lorenjohnson) [inline apps/web/src/components/HyloEditor/HyloEditor.js:38]: Moved extensions into their own variable for clarity, but not changes in this area

File: apps/web/src/components/HyloEditor/HyloEditor.js [hunk 2]
```diff
@@ -34,100 +34,124 @@ const HyloEditor = React.forwardRef(({
...
+    onCreate,
     onUpdate: ({ editor }) => {
       if (!onUpdate) return
-
       onUpdate(editor.getHTML())
     }
-  }, [placeholder, contentHTML]) // TODO: changing the placeholder resets the content of the editor which is probably not what we want
+  })
+
+  // Dynamic setting of initial editor content
```
Comment (lorenjohnson) [inline apps/web/src/components/HyloEditor/HyloEditor.js:131]: Changes how we set initial content, no longer re-creating the editor instance. This was a necessary part of this change, but is a better practice at this stage with TipTap.

File: apps/web/src/components/HyloEditor/HyloEditor.js [hunk 3]
```diff
@@ -34,100 +34,124 @@ const HyloEditor = React.forwardRef(({
...
+  useEffect(() => {
+    if (editor.isInitialized) {
+      editor.commands.setContent(contentHTML)
+    }
+  }, [editor?.isInitialized, contentHTML])
+
+  // Dynamic placeholder text
```
Comment (lorenjohnson) [inline apps/web/src/components/HyloEditor/HyloEditor.js:138]: As above, but for Placeholder text.

File: apps/web/src/components/HyloEditor/HyloEditorMobile.js [hunk 4]
```diff
@@ -101,7 +100,7 @@ export default function HyloEditorMobile (props) {
     className: 'hyloEditorMobile',
     onUpdate: handleUpdate,
     onEnter: handleEnter,
-    onBeforeCreate: handleBeforeCreate,
+    onCreate: handleCreate,
```
Comment (lorenjohnson) [inline apps/web/src/components/HyloEditor/HyloEditorMobile.js:103]: This is the key change, and only impacts HyloEditorMobile. Previously, likely because of different behaviour in an earlier version of TipTap, we handled setting the "loaded" state, which is the only thing we use this event for, via `onBeforeCreate`. That was too early now, so now hooking into `onCreate` to set editor loaded which HyloEditorMobile pays attention to to know when it can send editor updates through the WebView.

**Review by tibetsprague — APPROVED** [review]

**Review by thomasgwatson — APPROVED** [review]
lgtm
