### PR TITLE
chore(mobile): Fixes PostEditor and image/file display issues, nudges PostPresenter forward

### LINKED ISSUE #434: "Take Photo" functionality doesn't work in sim; check if it works in real-life
Low priority but would be nice to get to.

### PR DESCRIPTION
**Pull request by lorenjohnson**
- Fixes https://github.com/Hylozoic/hylo/issues/431. Currently only tested in iOS, but should fix Android as well a the issue was not platform specific. 
- Fixes #434
- Nudges PostPresenter forward, and adds some related notes for future work.
- Handles first requirement of https://github.com/Hylozoic/hylo/issues/143

### CODE REVIEW

File: packages/presenters/PostPresenter.js [hunk 1]
```diff
@@ -1,33 +1,48 @@
...
-    images,
-    files,
-    fileUrls: uniq(files.map(file => file.url)),
-    imageUrls: uniq(images.map(image => image.url)),
+    getAttachments: () => attachmentsResolver(post),
+    getImages: () => imagesResolver(post),
+    getFiles: () => filesResolver(post),
+    getFileUrls: () => uniq(filesResolver(post).map(file => file.url)),
+    getImageUrls: () => uniq(imagesResolver(post).map(image => image.url)),
+    // TODO: Research and reconcile start and endTimeRaw with their incoming values, both are currently
```
Comment (thomasgwatson) [inline packages/presenters/PostPresenter.js:16]: Yeah, recalling this was related to luxon changes getting brought into shared but not being tested in mobile, and so downstream there were divergent formats of the times needed.

**Review by thomasgwatson — APPROVED** [review]
lgtm
