### PR TITLE
1352 calendar inputs on mobile

### LINKED ISSUE #1352: Calender picker inputs do not work consistently on mobile (small UI?)

### PR DESCRIPTION
**Pull request by thomasgwatson**
Closes #1352

### CODE REVIEW

File: apps/web/src/components/ui/popover.jsx [hunk 1]
```diff
@@ -8,8 +8,8 @@ const PopoverTrigger = PopoverPrimitive.Trigger
 
 const PopoverArrow = PopoverPrimitive.Arrow
 
-const PopoverContent = React.forwardRef(({ className, align = 'center', sideOffset = 8, children, ...props }, ref) => (
-  <PopoverPrimitive.Portal>
+const PopoverContent = React.forwardRef(({ className, align = 'center', sideOffset = 8, container, children, ...props }, ref) => (
+  <PopoverPrimitive.Portal container={container}>
```
Comment (tibetsprague) [inline apps/web/src/components/ui/popover.jsx:12]: just double checking that this works fine when container is null

Comment (thomasgwatson) [reply apps/web/src/components/ui/popover.jsx:12]: Yeah, container is a standard part of the radix components interface, and it anticipates null

https://github.com/radix-ui/primitives/blob/22473d16404bfd446305db5b6c9308aece99fdec/packages/react/portal/src/portal.tsx#L18
